server:
  port: 8080

wso2:
  base-url: ${WSO2_BASE_URL}
  scim-users-endpoint: "/scim2/Users"
  username: ${WSO2_USERNAME:}
  password: ${WSO2_PASSWORD:}
  page-size: ${WSO2_PAGE_SIZE:50}

cymmetri:
  base-url: ${CYMMETRI_BASE_URL}
  username: ${CYMMETRI_USERNAME}
  password: ${CYMMETRI_PASSWORD}

spring:
  webclient:
    max-idle-time-millis: 30000

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    mappings:
      enabled: true
